amazon_scraper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static  # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'api/', include('api.urls')),
    url(r'^', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from rest_framework import routers

from .views import *

app_name = 'api'

router = routers.SimpleRouter()
router.register('requests', ScrapeRequestViewSet)

urlpatterns = router.urls

main/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('signup', views.Signup.as_view(), name='signup'),
    path('activate/<token>/', views.ActivateAccount.as_view(),
         name='activateaccount'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('change_password/', views.PasswordChange.as_view(), name='change_password'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('top', views.Top.as_view(), name="top"),
    path('newrequest', views.CreateScrapeRequest.as_view(), name="newrequest"),
    path('history', views.ListScrapeRequest.as_view(), name="history"),
    path('setting/<int:pk>/', views.Setting.as_view(), name="setting"),
    path('download', views.download, name="download"),
    path('deleterequest/<int:pk>/', views.delete_request, name='deleterequest'),
    path('results', views.ListScrapeRequestResult.as_view(), name='results'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('unsubscribe/<str:id>/', views.unsubscribe, name='unsubscribe'),

]

main/forms.py
from .models import User, ScrapeRequest, AppSettings
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django import forms
import io, re, csv
class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('email', 'last_name', 'first_name', 'seller_id', 'mws_auth_token','sp_api_refresh_token', 'market_place', 'password1', 'password2')

class UserUpdateForm(forms.ModelForm):
  """ユーザー情報更新フォーム"""
  class Meta:
    model = User
    fields = ('email', 'last_name', 'first_name', 'seller_id', 'mws_auth_token', 'sp_api_refresh_token', 'market_place', 'api_type', 'do_get_matching_product_for_id', 'do_get_competitive_pricing_for_asin', 'do_get_lowest_offer_listings_for_asin', 'do_get_my_price_for_asin', 'do_get_product_categories_for_asin', 'asin_jan_one_to_one')

class SettingUpdateForm(forms.ModelForm):
  """ユーザー情報更新フォーム"""
  class Meta:
    model = AppSettings
    fields = ('aws_access_key', "aws_secret_key", "sp_IAM_user_access_key", "sp_IAM_user_secret_key", "sp_api_client_id", "sp_api_client_secret","app_id")

class RequestTextForm(forms.ModelForm):
  class Meta:
    model = ScrapeRequest
    fields = ('id_type', 'id_text',)
  # text = forms.CharField(widget=forms.Textarea)
  
  def clean(self):
    data= super().clean()
    id_type = data['id_type']
    id_text = data['id_text']
    # pattern = r'^[A-Z0-9]{10}$' if id_type == 'asin' else r'^[0-9]{13}$' 
    # for index, id in enumerate(id_text.split('\r\n')):
    #   if not re.fullmatch(pattern, id):
    #     raise forms.ValidationError(f'{index + 1}個目のIDが不正です。...')
    return data
class RequestCsvForm(forms.ModelForm):
  class Meta:
    model = ScrapeRequest
    fields = ('id_type', 'csv_file',)
  
  def clean(self):
    data = super().clean()
    id_type = data['id_type']
    csv_file = data['csv_file']
    decoded_file = csv_file.read().decode('utf-8-sig')
    io_string = io.StringIO(decoded_file)

    pattern = r'^[A-Z0-9]{10}$' if id_type == 'asin' else r'^[0-9]{13}$' 
    for index, row in enumerate(csv.reader(io_string)):
      id = row[0].replace('\r', '')
      id = id.strip()
      if not re.fullmatch(pattern, id):
        raise forms.ValidationError(f'{index + 1}個目のIDが不正です。..')
    return data

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView
)
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView
from .forms import SignupForm, UserUpdateForm, RequestTextForm, RequestCsvForm, PasswordChangeForm, SettingUpdateForm
from .models import *
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import csv
from django.conf import settings
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives, send_mail
from django.core.signing import BadSignature, SignatureExpired, dumps, loads
from django.http import Http404, HttpResponseBadRequest, JsonResponse
from django.template.loader import get_template
from main.paypal_apis import get_client, create_subscription, cancel_subscription, list_billing_plans, update_subscription
import os
import datetime
import logging

import subprocess
import shlex
import json


def process_tasks():
    process_tasks_cmd = "python manage.py process_tasks &"
    process_tasks_args = shlex.split(process_tasks_cmd)
    process_tasks_subprocess = subprocess.Popen(process_tasks_args)


# emp=Employee.objects.get(EmployeeId=request.data.get("Emp"))
# process_tasks()


# Create your views here.
class Login(LoginView):
    """ログインページ"""
    template_name = 'login.html'


class Logout(LogoutView):
    pass


class Signup(CreateView):
    form_class = SignupForm
    template_name = "signup.html"
    success_url = reverse_lazy('top')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        # domain = current_site.domain
        # baseurl = f'{self.request.scheme}://{domain}'
        appsettings = AppSettings.load()
        baseurl = f'http://{appsettings.server_hostname}' if settings.DJANGO_ENV == 'prod' else 'http://localhost:8000'
        context = {
            'user': user,
            'baseurl': baseurl,
            'token': dumps(user.pk),
        }
        subject = 'ユーザ登録'
        # message = get_template('mail/signup.txt').render(context)
        # try:
        #     user.email_user(subject, message)
        # except Exception as e:
        #     print(e)
        #     messages.error(self.request, 'メール送信に失敗しました。')
        # else:
        #     messages.success(self.request, '仮登録しました。メールを確認し本登録を実施してください。')
        return redirect('main:signup')


class ActivateAccount(TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'activateaccount.html'
    timeout_seconds = 60*60*24  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)
        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'profile.html'

    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:profile', kwargs={'pk': self.kwargs['pk']})


class Setting(LoginRequiredMixin, UpdateView):
    model = AppSettings
    form_class = SettingUpdateForm
    template_name = 'setting.html'

    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:setting', kwargs={'pk': self.kwargs['pk']})


@login_required
def subscribe(request):
    appsettings = AppSettings.load()
    client = get_client(appsettings.paypal_client_id,
                        appsettings.paypal_client_secret)

    subscription_id = request.GET.get('subscription_id', None)
    ba_token = request.GET.get('ba_token', None)
    token = request.GET.get('token', None)

    if subscription_id:
        obj = PaypalSubscription.objects.get(subscription_id=subscription_id)
        obj = update_subscription(client, obj)
        obj.ba_token = ba_token
        obj.token = token
        obj.save()
        messages.success(request, '購読処理完了しました')
        return redirect('main:newrequest')

    else:
        plans = list_billing_plans(client)
        active_plans = [p for p in plans if p.status == 'ACTIVE']
        if len(active_plans) == 0:
            messages.error(request, "アクティブなプランが見つかりませんでした。")
            return redirect(reverse("main:newrequest"))

        plan_id = active_plans[0].id
        current_site = get_current_site(request)
        domain = current_site.domain
        return_url = f'http://{appsettings.server_hostname}{reverse("main:subscribe")}' if settings.DJANGO_ENV == 'prod' else 'http://127.0.0.1:8000/subscribe'

        try:
            subscription = create_subscription(
                client, request.user, plan_id, return_url=return_url, cancel_url=return_url)
        except Exception as e:
            print(f'error {e}')
            messages.error(request, str(e))
            return redirect(reverse('main:newrequest'))
        else:
            if not subscription:
                print('subscription is null ')
                messages.error(request, 'サブスクリプション作成に失敗しました。')
                return redirect(reverse('main:newrequest'))
            return redirect(subscription.approve_url)


@login_required
def unsubscribe(request, id):
    appsettings = AppSettings.load()
    client = get_client(appsettings.paypal_client_id,
                        appsettings.paypal_client_secret)

    subscription_id = request.GET.get('subscription_id', None)
    ba_token = request.GET.get('ba_token', None)
    token = request.GET.get('token', None)

    if subscription_id:
        obj = PaypalSubscription.objects.get(subscription_id=subscription_id)
        obj.ba_token = ba_token
        obj.token = token
        obj.save()
        messages.success(request, 'Unsubscrive successful')
        return redirect('main:profile', request.user.id)
    else:
        subscription = PaypalSubscription.objects.get(subscription_id=id)
        subscription = update_subscription(client, subscription)
        if not subscription:
            messages.error(request, 'サブスクリプション更新に失敗しました。')
            return redirect(reverse('main:newrequest'))

        if subscription.status == 'CANCELLED':
            messages.success(request, 'すでにキャンセル済みです。')
            return redirect(reverse('main:newrequest'))

        ret = cancel_subscription(client, subscription)
        if not ret:
            messages.error(request, 'サブスクリプションキャンセルに失敗しました。')
            return redirect(reverse('main:newrequest'))
        messages.success(request, 'サブスクリプションをキャンセルしました。')
        return redirect(reverse('main:newrequest'))


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = PasswordChangeForm
    success_url = reverse_lazy('main:change_password')
    template_name = 'password_change.html'

    def form_valid(self, form):
        messages.success(self.request, 'パスワード変更が完了しました。')
        return super().form_valid(form)


class Top(LoginRequiredMixin, TemplateView):
    template_name = 'top.html'


class CreateScrapeRequest(LoginRequiredMixin, TemplateView):
    template_name = 'scrape_request.html'
    print("__BB____"+template_name)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['use_paypal'] = AppSettings.load().use_paypal
        context['textform'] = RequestTextForm(
        ) if 'textform' not in kwargs else kwargs['textform']
        context['csvform'] = RequestCsvForm(
        ) if 'csvform' not in kwargs else kwargs['csvform']
        return context

    def get(self, *args, **kwargs):
        appsettings = AppSettings.load()
        if appsettings.use_paypal:
            client = get_client(appsettings.paypal_client_id,
                                appsettings.paypal_client_secret)
            if self.request.user.mysubscription:
                update_subscription(client, self.request.user.mysubscription)
        return super().get(*args, **kwargs)

    def post(self, *args, **kwargs):
        media = self.request.POST.get('media')
        if media == 'text':
            f = RequestTextForm(self.request.POST)
            if not f.is_valid():
                c = self.get_context_data(textform=f)
                return render(self.request, self.template_name, c)
        elif media == 'file':
            f = RequestCsvForm(self.request.POST, self.request.FILES)
            if not f.is_valid():
                c = self.get_context_data(csvform=f)
                return render(self.request, self.template_name, c)
        i = f.save(commit=False)
        i.user = self.request.user
        i.save()
        messages.success(self.request, '登録完了しました.')
        async_process_request(i.id)
        return redirect('main:history')


@login_required
def download(request):

main/templates/components/footer.html
<footer>

</footer>

main/templates/components/head.html
{% load static %}

<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<link href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.js"></script>
<link href="https://fonts.googleapis.com/css?family=M+PLUS+1p" rel="stylesheet">

<title>{% block title %}{% endblock %}</title>
<style>
  body {
    font-family: 'M PLUS 1p';
  }
</style>

main/templates/components/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light py-1">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">問屋ハンター</a>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav">

    </ul>
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <span class="btn welcome">
        ようこそ {{ user.username }} さん
      </span>
    
      <a class="btn logout_button" href="{% url 'main:logout' %}">
        Logout
      </a>
      {% else %}
      {% endif %}
    </ul>
  </div>
</nav>
<style>
  nav {
    border-bottom: solid lightgray 0.5px!important;
  }
  .navbar {
    height: 7vh;
  }


  
  
</style>

main/templates/components/pagination.html
{% if is_paginated %}
<nav class="mt-3" aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link"><i class="fa fa-chevron-left" aria-hidden="true"></i></span></li>
    {% endif %}
    
    {% if page_obj.number|add:'-4' > 1 %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'-5' }}">&hellip;</a></li>
    {% endif %}
    
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
      {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    
    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.number|add:'5' }}">&hellip;</a></li>
    {% endif %}
    
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link"><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
    {% endif %}
  </ul>  
</nav>
<style>
  nav {
    border-bottom: none;
  }
</style>
{% endif %}

main/templates/components/sidebar.html
<div class="bg-light border-right" id="sidebar-wrapper">
  <div class="list-group list-group-flush">
    <a href="{% url 'main:profile' user.pk %}" class="list-group-item list-group-item-action bg-light {% if 'profile' in request.path %}active{% endif %}">登録情報</a>
    <a href="{% url 'main:newrequest' %}" class="list-group-item list-group-item-action bg-light {% if 'newrequest' in request.path %}active{% endif %}">新規リクエスト</a>
    <a href="{% url 'main:history' %}" class="list-group-item list-group-item-action bg-light {% if 'history' in request.path %}active{% endif %}">リクエスト一覧</a>
    {% if user.username == "aldecino@gmail.com" %}
    <a href="{% url 'main:setting' 1 %}" class="list-group-item list-group-item-action bg-light {% if 'setting' in request.path %}active{% endif %}">設定</a>  
    {% endif %}  
    <!-- <a href="{% url 'main:results' %}" class="list-group-item list-group-item-action bg-light {% if 'results' in request.path %}active{% endif %}">リクエスト結果</a> -->
  </div>
</div>
<style>
  /*!
 * Start Bootstrap - Simple Sidebar (https://startbootstrap.com/template-overviews/simple-sidebar)
 * Copyright 2013-2019 Start Bootstrap
 * Licensed under MIT (https://github.com/BlackrockDigital/startbootstrap-simple-sidebar/blob/master/LICENSE)
 */

  #sidebar-wrapper {
    min-height: 93vh;
    margin-left: -15rem;
    -webkit-transition: margin .25s ease-out;
    -moz-transition: margin .25s ease-out;
    -o-transition: margin .25s ease-out;
    transition: margin .25s ease-out;
  }

  #sidebar-wrapper .sidebar-heading {
    padding: 0.875rem 1.25rem;
    font-size: 1.2rem;
  }

  #sidebar-wrapper .list-group {
    width: 15rem;
  }

  #page-content-wrapper {
    min-width: 100vw;
  }

  #wrapper.toggled #sidebar-wrapper {
    margin-left: 0;
  }
  .list-group-item.active {
    color: black;
    font-weight: bold;
  }
  @media (min-width: 768px) {
    #sidebar-wrapper {
      margin-left: 0;
    }

    #page-content-wrapper {
      min-width: 0;
      width: 100%;
    }

    #wrapper.toggled #sidebar-wrapper {
      margin-left: -15rem;
    }
  }

</style>