amazon_scraper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static  # 追加

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'api/', include('api.urls')),
    url(r'^', include('main.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from rest_framework import routers

from .views import *

app_name = 'api'

router = routers.SimpleRouter()
router.register('requests', ScrapeRequestViewSet)

urlpatterns = router.urls

main/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('signup', views.Signup.as_view(), name='signup'),
    path('activate/<token>/', views.ActivateAccount.as_view(),
         name='activateaccount'),
    path('profile/<int:pk>/', views.Profile.as_view(), name='profile'),
    path('change_password/', views.PasswordChange.as_view(), name='change_password'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('top', views.Top.as_view(), name="top"),
    path('newrequest', views.CreateScrapeRequest.as_view(), name="newrequest"),
    path('history', views.ListScrapeRequest.as_view(), name="history"),
    path('setting/<int:pk>/', views.Setting.as_view(), name="setting"),
    path('download', views.download, name="download"),
    path('deleterequest/<int:pk>/', views.delete_request, name='deleterequest'),
    path('results', views.ListScrapeRequestResult.as_view(), name='results'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('unsubscribe/<str:id>/', views.unsubscribe, name='unsubscribe'),

]

main/forms.py
from .models import User, ScrapeRequest, AppSettings
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django import forms
import io, re, csv
class SignupForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('email', 'last_name', 'first_name', 'seller_id', 'mws_auth_token','sp_api_refresh_token', 'market_place', 'password1', 'password2')

class UserUpdateForm(forms.ModelForm):
  """ユーザー情報更新フォーム"""
  class Meta:
    model = User
    fields = ('email', 'last_name', 'first_name', 'seller_id', 'mws_auth_token', 'sp_api_refresh_token', 'market_place', 'api_type', 'do_get_matching_product_for_id', 'do_get_competitive_pricing_for_asin', 'do_get_lowest_offer_listings_for_asin', 'do_get_my_price_for_asin', 'do_get_product_categories_for_asin', 'asin_jan_one_to_one')

class SettingUpdateForm(forms.ModelForm):
  """ユーザー情報更新フォーム"""
  class Meta:
    model = AppSettings
    fields = ('aws_access_key', "aws_secret_key", "sp_IAM_user_access_key", "sp_IAM_user_secret_key", "sp_api_client_id", "sp_api_client_secret","app_id")

class RequestTextForm(forms.ModelForm):
  class Meta:
    model = ScrapeRequest
    fields = ('id_type', 'id_text',)
  # text = forms.CharField(widget=forms.Textarea)
  
  def clean(self):
    data= super().clean()
    id_type = data['id_type']
    id_text = data['id_text']
    # pattern = r'^[A-Z0-9]{10}$' if id_type == 'asin' else r'^[0-9]{13}$' 
    # for index, id in enumerate(id_text.split('\r\n')):
    #   if not re.fullmatch(pattern, id):
    #     raise forms.ValidationError(f'{index + 1}個目のIDが不正です。...')
    return data
class RequestCsvForm(forms.ModelForm):
  class Meta:
    model = ScrapeRequest
    fields = ('id_type', 'csv_file',)
  
  def clean(self):
    data = super().clean()
    id_type = data['id_type']
    csv_file = data['csv_file']
    decoded_file = csv_file.read().decode('utf-8-sig')
    io_string = io.StringIO(decoded_file)

    pattern = r'^[A-Z0-9]{10}$' if id_type == 'asin' else r'^[0-9]{13}$' 
    for index, row in enumerate(csv.reader(io_string)):
      id = row[0].replace('\r', '')
      id = id.strip()
      if not re.fullmatch(pattern, id):
        raise forms.ValidationError(f'{index + 1}個目のIDが不正です。..')
    return data

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView
)
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView
from .forms import SignupForm, UserUpdateForm, RequestTextForm, RequestCsvForm, PasswordChangeForm, SettingUpdateForm
from .models import *
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import csv
from django.conf import settings
from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMultiAlternatives, send_mail
from django.core.signing import BadSignature, SignatureExpired, dumps, loads
from django.http import Http404, HttpResponseBadRequest, JsonResponse
from django.template.loader import get_template
from main.paypal_apis import get_client, create_subscription, cancel_subscription, list_billing_plans, update_subscription
import os
import datetime
import logging

import subprocess
import shlex
import json


def process_tasks():
    process_tasks_cmd = "python manage.py process_tasks &"
    process_tasks_args = shlex.split(process_tasks_cmd)
    process_tasks_subprocess = subprocess.Popen(process_tasks_args)


# emp=Employee.objects.get(EmployeeId=request.data.get("Emp"))
# process_tasks()


# Create your views here.
class Login(LoginView):
    """ログインページ"""
    template_name = 'login.html'


class Logout(LogoutView):
    pass


class Signup(CreateView):
    form_class = SignupForm
    template_name = "signup.html"
    success_url = reverse_lazy('top')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        # domain = current_site.domain
        # baseurl = f'{self.request.scheme}://{domain}'
        appsettings = AppSettings.load()
        baseurl = f'http://{appsettings.server_hostname}' if settings.DJANGO_ENV == 'prod' else 'http://localhost:8000'
        context = {
            'user': user,
            'baseurl': baseurl,
            'token': dumps(user.pk),
        }
        subject = 'ユーザ登録'
        # message = get_template('mail/signup.txt').render(context)
        # try:
        #     user.email_user(subject, message)
        # except Exception as e:
        #     print(e)
        #     messages.error(self.request, 'メール送信に失敗しました。')
        # else:
        #     messages.success(self.request, '仮登録しました。メールを確認し本登録を実施してください。')
        return redirect('main:signup')


class ActivateAccount(TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'activateaccount.html'
    timeout_seconds = 60*60*24  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)
        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class Profile(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'profile.html'

    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:profile', kwargs={'pk': self.kwargs['pk']})


class Setting(LoginRequiredMixin, UpdateView):
    model = AppSettings
    form_class = SettingUpdateForm
    template_name = 'setting.html'

    def form_valid(self, form):
        messages.success(self.request, '更新が完了しました')
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('main:setting', kwargs={'pk': self.kwargs['pk']})


@login_required
def subscribe(request):
    appsettings = AppSettings.load()
    client = get_client(appsettings.paypal_client_id,
                        appsettings.paypal_client_secret)

    subscription_id = request.GET.get('subscription_id', None)
    ba_token = request.GET.get('ba_token', None)
    token = request.GET.get('token', None)

    if subscription_id:
        obj = PaypalSubscription.objects.get(subscription_id=subscription_id)
        obj = update_subscription(client, obj)
        obj.ba_token = ba_token
        obj.token = token
        obj.save()
        messages.success(request, '購読処理完了しました')
        return redirect('main:newrequest')

    else:
        plans = list_billing_plans(client)
        active_plans = [p for p in plans if p.status == 'ACTIVE']
        if len(active_plans) == 0:
            messages.error(request, "アクティブなプランが見つかりませんでした。")
            return redirect(reverse("main:newrequest"))

        plan_id = active_plans[0].id
        current_site = get_current_site(request)
        domain = current_site.domain
        return_url = f'http://{appsettings.server_hostname}{reverse("main:subscribe")}' if settings.DJANGO_ENV == 'prod' else 'http://127.0.0.1:8000/subscribe'

        try:
            subscription = create_subscription(
                client, request.user, plan_id, return_url=return_url, cancel_url=return_url)
        except Exception as e:
            print(f'error {e}')
            messages.error(request, str(e))
            return redirect(reverse('main:newrequest'))
        else:
            if not subscription:
                print('subscription is null ')
                messages.error(request, 'サブスクリプション作成に失敗しました。')
                return redirect(reverse('main:newrequest'))
            return redirect(subscription.approve_url)


@login_required
def unsubscribe(request, id):
    appsettings = AppSettings.load()
    client = get_client(appsettings.paypal_client_id,
                        appsettings.paypal_client_secret)

    subscription_id = request.GET.get('subscription_id', None)
    ba_token = request.GET.get('ba_token', None)
    token = request.GET.get('token', None)

    if subscription_id:
        obj = PaypalSubscription.objects.get(subscription_id=subscription_id)
        obj.ba_token = ba_token
        obj.token = token
        obj.save()
        messages.success(request, 'Unsubscrive successful')
        return redirect('main:profile', request.user.id)
    else:
        subscription = PaypalSubscription.objects.get(subscription_id=id)
        subscription = update_subscription(client, subscription)
        if not subscription:
            messages.error(request, 'サブスクリプション更新に失敗しました。')
            return redirect(reverse('main:newrequest'))

        if subscription.status == 'CANCELLED':
            messages.success(request, 'すでにキャンセル済みです。')
            return redirect(reverse('main:newrequest'))

        ret = cancel_subscription(client, subscription)
        if not ret:
            messages.error(request, 'サブスクリプションキャンセルに失敗しました。')
            return redirect(reverse('main:newrequest'))
        messages.success(request, 'サブスクリプションをキャンセルしました。')
        return redirect(reverse('main:newrequest'))


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = PasswordChangeForm
    success_url = reverse_lazy('main:change_password')
    template_name = 'password_change.html'

    def form_valid(self, form):
        messages.success(self.request, 'パスワード変更が完了しました。')
        return super().form_valid(form)


class Top(LoginRequiredMixin, TemplateView):
    template_name = 'top.html'


class CreateScrapeRequest(LoginRequiredMixin, TemplateView):
    template_name = 'scrape_request.html'
    print("__BB____"+template_name)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['use_paypal'] = AppSettings.load().use_paypal
        context['textform'] = RequestTextForm(
        ) if 'textform' not in kwargs else kwargs['textform']
        context['csvform'] = RequestCsvForm(
        ) if 'csvform' not in kwargs else kwargs['csvform']
        return context

    def get(self, *args, **kwargs):
        appsettings = AppSettings.load()
        if appsettings.use_paypal:
            client = get_client(appsettings.paypal_client_id,
                                appsettings.paypal_client_secret)
            if self.request.user.mysubscription:
                update_subscription(client, self.request.user.mysubscription)
        return super().get(*args, **kwargs)

    def post(self, *args, **kwargs):
        media = self.request.POST.get('media')
        if media == 'text':
            f = RequestTextForm(self.request.POST)
            if not f.is_valid():
                c = self.get_context_data(textform=f)
                return render(self.request, self.template_name, c)
        elif media == 'file':
            f = RequestCsvForm(self.request.POST, self.request.FILES)
            if not f.is_valid():
                c = self.get_context_data(csvform=f)
                return render(self.request, self.template_name, c)
        i = f.save(commit=False)
        i.user = self.request.user
        i.save()
        messages.success(self.request, '登録完了しました.')
        async_process_request(i.id)
        return redirect('main:history')


@login_required
def download(request):

main/templates/activateaccount.html
<html>
<head>
  {% include "components/head.html" %}
  <style>
  </style>
</head>
<body class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6 offset-3">
        <H1>アクティベーションが完了しました！</H1>
        <a href="{% url 'main:login' %}" class="btn btn-primary">Loginページへ</a>
      </div>
    </div>
  </div>
</body>
</html>

main/templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
<head>
  {% include "components/head.html" %}
  <style>
    .wrapper {
      height: 93vh;
      display: flex;
      align-items: stretch; 
      
    }
    .content {
      width: 100%;
      height: 100%;
      padding: 1rem 1rem;
      overflow-y: auto;
      
    }

    th {
      white-space: nowrap;
    }
    th {
      position: sticky; top: 0;
      background-color: white;
    }
  </style>
</head>
<body>
  {% include 'components/navbar.html' %}
  <div class="wrapper">
    {% include "components/sidebar.html" %}
    <div class="content">
      {% if messages %}
        {% for message in messages %}
          <div class="{{ message|bootstrap_message_classes }} alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&#215;</button>
              {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% block pagetitle %}{% endblock %}
      <hr>
      {% block content %}{% endblock %}
      {% include 'components/pagination.html' %}
    </div>  
  </div>
  {% block style %}{% endblock %}
  <script>
    function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          var cookies = document.cookie.split(';');
          for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
      beforeSend: function (xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });

    var type = window.location.hash.substr(1);
    if (type) {
      $(`#${type}-tab`).click();
    }
  </script>

  {% block script %}{% endblock %}
</body>
</html>

main/templates/login.html
{% load crispy_forms_tags %}
<html>
<head>
  {% include "components/head.html" %}
  <style>
    .login-col {
      height: 100vh;
    }
  </style>
</head>
<body class="bg-light">
  <div class="container pt-5">
    <div class="row">
      <div class="col-6 offset-3">
        <h2 class="text-center">Login</h2>
        <div class="card shadow p-3">
          <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary">Login</button>
            <span>or</span>
            <a href="{% url 'main:signup' %}" class="">Signup</a>
          </form>
         
        </div>
      </div>
    </div>
  </div>
</body>
</html>

main/templates/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Top{% endblock %}

{% block style %}
  <style>
   
  </style>
{% endblock %}

{% block pagetitle %}
  <H6>Password Change</H6>
{% endblock %}

{% block content %}
<div class="col-6">
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-success">変更</button>
  </form>    
</div>
{% endblock %}

{% block script %}
<script>
  $(function() {
    
  });
</script>

{% endblock %}

main/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Top{% endblock %}

{% block style %}
  <style>
   
  </style>
{% endblock %}

{% block pagetitle %}
  <H6>Profile</H6>
{% endblock %}
{% block content %}
<div class="col-6">
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-success">更新</button>
  </form>
  <p>パスワード変更は<a href="{% url 'main:change_password' %}">こちら</a> </p>
</div>

{% endblock %}

{% block script %}
<script>
  $(function() {
    
  });
</script>

{% endblock %}

main/templates/request_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load myfilters %}
{% block title %}Top{% endblock %}

{% block style %}
  <style>
    .operation-form {
      display: inline-block;
    }

  </style>
{% endblock %}


{% block pagetitle %}
  <H6>Request List</H6>
{% endblock %}

{% block content %}
<div class="table-responsive card shadow p-2">
  <table class="table table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>ID Type</th>
        <th>Count</th>
        <th>Date Requested</th>
        <th>Status</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for o in object_list %}
        <tr>
          <td>{{ o.id }}</td>
          <td>{{ o.id_type }}</td>
          <td>{{ o.id_count }}</td>
          <td>{{ o.requested_at | date:"Y/n/j H:i" }}</td>
          <td>
            <span class="badge badge-pill {{ o.status_badge_class }}">
            {{ o.status_text }}
            </span>
          </td>
          <td style="white-space: nowrap;">
            {% if o.downloadable %}
            <form class="operation-form">
              <button type="button" data-toggle="modal" data-target="#download-modal" data-request-id="{{ o.id }}" class="btn btn-sm btn-primary"><i class="fas fa-file-download"></i></button>
            </form>
            {% endif %}
            
            <form class="operation-form" method="post" action="{% url 'main:deleterequest' o.pk %}">
              {% csrf_token %}
              <button class="btn btn-sm btn-danger"><i class="fas fa-trash-alt"></i></button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button> -->

<div class="modal fade" id="download-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Download CSV</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" action="{% url 'main:download' %}">
        <!-- <form method="post"> -->
          {% csrf_token %}
          <input type="hidden" id="request-id" name="request-id" value="">
          <div class="form-group">
            <label for="message-text" class="col-form-label">Encoding:</label>
            <select name="encoding" class="form-control form-control-sm">
              <option selected value="cp932">cp932(Shift-JIS)</option>
              <option value="utf-8">UTF-8</option>
            </select>
          </div>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Download</button>
       
        </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script>
  $(function() {
    $('#download-modal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var request_id = button.data('request-id') // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this)
      modal.find('.modal-body input#request-id').val(request_id)
    })
  });
</script>

{% endblock %}

main/templates/scrape_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Top{% endblock %}

{% block style %}
  <style>


  </style>
{% endblock %}


{% block pagetitle %}
  <H6>New Request</H6>
{% endblock %}

{% block content %}
  {% if not user.subscribing %}
    {% if use_paypal %}
    <span>有効なサブスクリプションが見つかりませんでした</span><a class="btn btn-primary" href="{% url 'main:subscribe' %}">購読する</a>
    {% else %}
    <span>利用権限がありません。管理者にお問い合わせください。</span>
    {% endif %}
  {% else %}
    <div class="row">
      <div class="col-6">
        <div class="card shadow p-3">
          <form method="post">
            <input type="hidden" name="media" value="text">
            {% csrf_token %}
            {{ textform | crispy }}
            <button class="btn btn-sm btn-success shadow">Request</button>
          </form>    
        </div>
      </div>
      <div class="col-6">
        <div class="card shadow p-3">
          <form method="post" enctype='multipart/form-data'>
            <input type="hidden" name="media" value="file">
            {% csrf_token %}
            {{ csvform | crispy }}
            <button class="btn btn-sm btn-success shadow">Request</button>
          </form>
        </div>    
      </div>
    </div>
    {% if use_paypal and not user.is_superuser %}
    <a class="btn btn-danger mt-2 shadow" href="{% url 'main:unsubscribe' user.mysubscription.subscription_id %}">購読をキャンセルする</a>
    {% endif %}
  {% endif %}
{% endblock %}

{% block script %}
<script>
  $(function() {
    
  });
</script>

{% endblock %}

main/templates/setting.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Top{% endblock %}

{% block style %}
  <style>
   
  </style>
{% endblock %}

{% block pagetitle %}
  <H6>Setting</H6>
{% endblock %}
{% block content %}
<div class="col-6">
  <form method="post">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-success">更新</button>
  </form>
</div>

{% endblock %}

{% block script %}
<script>
  $(function() {
    
  });
</script>

{% endblock %}

main/templates/signup.html
{% load crispy_forms_tags %}
<html>
<head>
  {% include "components/head.html" %}
  <style>

  </style>
</head>
<body class="bg-light">
  <div class="container pt-5">
    <div class="row">
      <div class="col-6 offset-3">
        <h2 class="text-center">Sign Up</h2>
        <div class="card shadow p-4">
          {% if messages %}
            {% for message in messages %}
              <div class="{{ message|bootstrap_message_classes }} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&#215;</button>
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post">
            {% csrf_token %}
            {{ form | crispy }}
            <button class="btn btn-primary">Signup</button>
            <span>or</span>
            <a href="{% url 'main:login' %}" class="">Login</a>
          
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

main/templates/top.html
{% extends 'base.html' %}

{% block title %}Top{% endblock %}

{% block style %}
  <style>
   
  </style>
{% endblock %}

{% block pagetitle %}{{ pagetitle }}{% endblock %}
{% block content %}

<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="upload-tab" data-toggle="tab" href="#upload" role="tab" aria-controls="upload" aria-selected="true">ファイル</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="rawdata-tab" data-toggle="tab" href="#rawdata" role="tab" aria-controls="rowdata" aria-selected="false">データ</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="itemcount-tab" data-toggle="tab" href="#itemcount" role="tab" aria-controls="itemcount" aria-selected="false">出品数/有効在庫数</a>
  </li>
</ul>
<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="upload" role="tabpanel" aria-labelledby="upload-tab">
   
  </div>
  <div class="tab-pane fade" id="rawdata" role="tabpanel" aria-labelledby="rawdata-tab">
    
  </div>
  <div class="tab-pane fade" id="itemcount" role="tabpanel" aria-labelledby="itemcount-tab">
  </div> 
</div>
{% endblock %}

{% block script %}
<script>
  $(function() {
    
  });
</script>

{% endblock %}